// Category
export const GETCATEGORY = "GETCATEGORY";
export const POSTCATEGORY = "POSTCATEGORY";
export const DELETECATEGORY = "DELETECATEGORY";

// Melting
export const GETMELTING = "GETMELTING";
export const POSTMELTING = "POSTMELTING";
export const DELETEMELTING = "DELETEMELTING";

// SubCategory
export const GETSUBCATEGORY = "GETSUBCATEGORY";
export const POSTSUBCATEGORY = "POSTSUBCATEGORY";
export const DELETESUBCATEGORY = "DELETESUBCATEGORY";

// Products
export const GETPRODUCTS = "GETPRODUCTS";
export const POSTPRODUCTS = "POSTPRODUCTS";
export const DELETEPRODUCTS = "DELETEPRODUCTS";

// auth

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// liverate

export const GETLIVEGOLDRATE = "GETLIVEGOLDRATE";
export const POSTLIVEGOLDRATE = "POSTLIVEGOLDRATE";
export const DELETELIVEGOLDRATE = "DELETELIVEGOLDRATE";
export const GETLIVESILVERRATE = "GETLIVESILVERRATE";
export const POSTLIVESILVERRATE = "POSTLIVESILVERRATE";
export const DELETELIVESILVERRATE = "DELETELIVESILVERRATE";


// banner

export const GETBANNER = "GETBANNER";
export const POSTBANNER = "POSTBANNER";
export const DELETEBANNER = "DELETEBANNER";

export const GETTOPPOST = "GETTOPPOST";
export const POSTTOPPOST = "POSTTOPPOST";
export const DELETETOPPOST = "DELETETOPPOST";
